#!/bin/bash

. ./config.sh

lb_config="lb config noauto \
	--bootstrap-flavour standard \
	--binary-images iso-hybrid \
	--iso-preparer Debian \
	--iso-application PrivCoin \
	--bootappend-live \"live-config.hooks=medium noprompt locales=${LOCALE} keyboard-layouts=${KEYBOARD}\" \
	--archive-areas \"main contrib non-free\" \
	--tasksel none \
	--includes none \
	--security true \
	--apt-recommends false \
	--apt-indices false \
	--debian-installer false \
	--memtest none \
	--cache-indices false "



function preConfig() {
	echo "===PreConfig==="
}

function postConfig() {
	echo "===PostConfig==="	

	if $PRIVACY_KERNEL; then
		cp /usr/share/live/build/examples/hooks/all_chroot_update-initramfs.sh ./config/hooks/099-update-initramfs.chroot
	fi
	
	echo "Copy config-source"
	cp -rf ./src/* ./config

	if $BUILD_FOR_CD; then
		echo "Disable mountable root patch"
		mv ./config/includes.chroot/usr/share/privcoin/patches/mountscript.patch ./config/includes.chroot/usr/share/privcoin/patches/mountscript.patch.off
		rm ./config/includes.binary/live/hooks/remount-rw
	fi

	if $NO_VIRTUALBOX; then
		echo "Delete virtualbox package list"
		rm ./config/package-lists/virtualbox.list.chroot
	fi

	echo "Copy lb buildscripts"
	if [[ ! -d local/live-build ]]; then	
		mkdir local/live-build
		cp -r /usr/share/live/build/* local/live-build
		patch -p0 < auto/lb_binary.patch
	fi
}

preConfig "${@}"

echo "===Config==="
eval $lb_config

postConfig
